services:
  postgres:
    image: postgres
    container_name: postgresBIGDatalab1
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: user      # ${DB_USER}
      POSTGRES_PASSWORD: psswd       # ${DB_PASSWORD}
      POSTGRES_DB: postgresDB        # ${DB_NAME}
    volumes:
      - './solution/:/docker-entrypoint-initdb.d/'
    # command: ["postgres", "-c", "log_statement=all"]
